apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: quiz-app
resources:
  - postgres-deployment.yaml
  - postgres-service.yaml
  - postgres-volume-persistentvolumeclaim.yaml
  - quiz-app-backend-deployment.yaml
  - quiz-app-backend-ingress.yaml
  - quiz-app-backend-service.yaml
  - quiz-app-frontend-deployment.yaml
  - quiz-app-frontend-ingress.yaml
  - quiz-app-frontend-service.yaml
  - quiz-app-namespace.yaml
  - secret-env-configmap.yaml
